# -*- mode: yaml; -*-
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

INHERIT: .config/copier/mkdocs.yaml
site_name: "Lollipop"
site_description: TODO

plugins:
  mkdocstrings:
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
