# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!

# ref: <https://docs.pytest.org/en/stable/>


def inc(x: int) -> int:
    return x + 1


def test_answer() -> None:
    assert inc(3) == 4
